In [1]:
import re  
import nltk
import string
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

pd.set_option("display.max_colwidth",200)
warnings.filterwarnings("ignore",category=DeprecationWarning)

In [2]:
train = pd.read_csv('train_F3WbcTw.csv')
train.head()

unique_hash  \
0  2e180be4c9214c1f5ab51fd8cc32bc80c9f612e0   
1  9eba8f80e7e20f3a2f48685530748fbfa95943e4   
2  fe809672251f6bd0d986e00380f48d047c7e7b76   
3  bd22104dfa9ec80db4099523e03fae7a52735eb6   
4  b227688381f9b25e5b65109dd00f7f895e838249   

                                                                                                                                                                                                      text  \
0  Autoimmune diseases tend to come in clusters. As for Gilenya – if you feel good, don’t think about it, it won’t change anything but waste your time and energy. I’m taking Tysabri and feel amazing,...   
1  I can completely understand why you’d want to try it. But, results reported in lectures don’t always stand up to the scrutiny of peer-review during publication. There so much still to do before th...   
2  Interesting that it only targets S1P-1/5 receptors rather than 1-5 like Fingolimod. Hoping to soon see what the AEs and SAEs were Yes. I'm not sure what this means, exactly:  Quote Nine patients r...   
3                                                                             Very interesting, grand merci. Now I wonder where lemtrada and ocrevus sales would go, if they prove anti-cd20 are induction   
4  Hi everybody, My latest MRI results for Brain and Cervical Cord are in and my next Neurologist appointment is in the next couple of weeks. There’re no new lesions in Brain/Cord and I’ve had no rel...   

         drug  sentiment  
0     gilenya          2  
1     gilenya          2  
2  fingolimod          2  
3     ocrevus          2  
4     gilenya          1

In [3]:
test = pd.read_csv('test_tOlRoBf.csv')
test.head()

unique_hash  \
0  9e9a8166b84114aca147bf409f6f956635034c08   
1  e747e6822c867571afe7b907b51f0f2ca67b0e1a   
2  50b6d851bcff4f35afe354937949e9948975adf7   
3  7f82ec2176ae6ab0b5d20b5ffc767ac829f384ae   
4  8b37d169dee5bdae27060949242fb54feb6a7f7f   

                                                                                                                                                                                                      text  \
0                                                                                                                                 256 (previously stable on natalizumab), with 55% switching to fingolimod   
1                                                       On fingolimod and have been since December 2015; the only way I can describe it any better is like feeling drunk but without having had a drink!!!   
2  Apparently it's shingles! :-/ I do have a few red spots just below my left breast which appeared a few days ago. Wasn't sure if they were connected or not, but showed them to the GP and he immedia...   
3  If the Docetaxel doing once a week x3 weeks then 1 week off (claim to be less harsh), will it have the same efficacy as the once every 3 weeks?   Diagnosed in 2014 stage 4 nsclc. EGFR+ (also posit...   
4  CC, Stelara worked in a matter of days for me. If your GI is willing to jump through hoops to get it for you then it’s probably worth considering. If one anti tnf stopped working for you then anot...   

         drug  
0  fingolimod  
1  fingolimod  
2      humira  
3    tagrisso  
4     stelara

In [4]:
print(train.shape)
print(test.shape)

(5279, 4)
(2924, 3)


In [33]:
train.sentiment.value_counts()  

2    3825
1     837
0     617
Name: sentiment, dtype: int64

#### Imbalanced class problem.
1. Random Under Sampling 

In [73]:
# Class count
count_class_2, count_class_1 ,count_class_0 = train.sentiment.value_counts()

# Divide by class
class_0 = train[train.sentiment == 0]
class_1 =train[train.sentiment == 1]
class_2 = train[train.sentiment == 2]
class_2_under = class_2.sample(count_class_1)
train_under = pd.concat([class_2_under, class_1,class_0], axis=0)

print('Random under-sampling:')
#print(df_test_under.sentiment.value_counts())
print(train1.sentiment.value_counts())

Random under-sampling:
1    837
2    837
0    617
Name: sentiment, dtype: int64


2. Random Over Sampling 

In [ ]:
class_0_over = class_0.sample(count_class_2, replace=True)
class_1_over = class_1.sample(count_class_2, replace=True)
train_over = pd.concat([class_2, class_1_over , class_0_over], axis=0)

print('Random under-sampling:')
#print(df_test_under.sentiment.value_counts())
print(train1.sentiment.value_counts())

In [36]:
print(train_under.shape)
print(train_over.shape)

(2291, 4)

In [37]:
train_new.isna().sum()

unique_hash    0
text           0
drug           0
sentiment      0
dtype: int64

In [6]:
#Undersampling is giving more accurate result
combi = train.append(test , ignore_index=True)
#combi = train_over.append(test , ignore_index=True)
combi.shape

C:\Users\Public\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


(8203, 4)

In [58]:
combi['drug'].value_counts()

gilenya                         697
ocrevus                         629
ocrelizumab                     362
entyvio                         303
humira                          289
remicade                        276
opdivo                          223
tarceva                         215
fingolimod                      202
keytruda                        198
tagrisso                        189
cladribine                      174
stelara                         163
alimta                          140
lucentis                         80
eylea                            57
avastin                          53
cimzia                           50
alectinib                        45
erlotinib                        41
nivolumab                        39
simponi                          38
crizotinib                       37
vitrectomy                       36
pembrolizumab                    35
xalkori                          33
mavenclad                        31
tecentriq                   

In [60]:
combi.columns

Index(['unique_hash', 'text', 'drug', 'sentiment', 'tidy_text'], dtype='object')

In [7]:
#Encoding Drug Column
from sklearn.preprocessing import LabelEncoder
encode=LabelEncoder()
combi.iloc[:,2]=encode.fit_transform(combi.iloc[:,2])

In [ ]:
#Cleaning Text Column
combi['tidy_text'] = combi['text'].str.replace(r"http\S+", "")
combi['tidy_text'] = combi['tidy_text'].str.replace(r"http", "")
combi['tidy_text'] = combi['tidy_text'].str.replace(r"(\d)", "")
combi['tidy_text'] = combi['tidy_text'].str.replace(r"@\S+", "")
combi['tidy_text'] = combi['tidy_text'].str.replace(r"[^A-Za-z0-9(),!?@\'\`\"\_\n]", " ")
combi['tidy_text'] = combi['tidy_text'].str.replace(r"@", "at")
combi['tidy_text'] = combi['tidy_text'].str.lower()

In [77]:
from nltk.corpus import stopwords

In [78]:
stop = stopwords.words('english')
combi['tidy_text']=combi['tidy_text'].apply(lambda x : " ".join([w for w in x.split() if w.lower() not in stop]))
combi.head()

unique_hash  \
0  4d95c5ec996f8c2329865bf7e94aad11ec7d7c8c   
1  f6ccc04eadefc43e3079a471c7c5bce8a10cd944   
2  b72ecb1805f926ca9e8b5d92a1e81b96f43a5e84   
3  5261dd6ea6b16be98d44ac5a51dc13fb299be3e8   
4  163409436fce5b7f662a743024fbdd0ae5a32f87   

                                                                                                                                                                                                      text  \
0  Hello @mermaidia11 , I get that completely. I am not PPMS myself, but I really just believe that PPMS folk should at least have the choice, as they do in the US, Canada and Europe. I take Tecfider...   
1  I just read this entire thread. I am going to be starting on Entyvio as soon as insurance oks. This will be my first (hopefully last!) biologic. The reason I chose this is because it's not suppose...   
2  Tuesday 03.28.17 - 8:33pm ET The FDA approved Genentech’s OCREVUS  TM (ocrelizumab) for people with relapsing or primary progressive forms of multiple sclerosis (MS). This is the first and only ap...   
3  Hi Mohit, Welcome to GRACE. I am sorry to hear of the recent progression of your father’s lung cancer. Though there are some oncologists who like to continue Tarceva even after progression, combin...   
4  Comment: Diagnosed with wet ARMD about a year ago. Was switched to Eylea several months ago. It initially had a profound impact reducing the wet leakage but not entirely. Leakage returned when a b...   

   drug  sentiment  \
0    65          2   
1    32          2   
2    65          2   
3    91          2   
4    35          2   

                                                                                                                                                                                                 tidy_text  
0  hello , get completely ppms myself, really believe ppms folk least choice, us, canada europe take tecfidera, complications, including deaths reported taking risk balance chosen take people died ta...  
1  read entire thread going starting entyvio soon insurance oks first (hopefully last!) biologic reason chose supposed systemic hopefully make prone colds that's biggest worry biologic long term yo f...  
2  tuesday pm et fda approved genentech ocrevus tm (ocrelizumab) people relapsing primary progressive forms multiple sclerosis (ms) first approved treatment primary progressive ms (ppms) , one disabl...  
3  hi mohit, welcome grace sorry hear recent progression father lung cancer though oncologists like continue tarceva even progression, combining drug alimta (pemetrexed), often progression significan...  
4  comment diagnosed wet armd year ago switched eylea several months ago initially profound impact reducing wet leakage entirely leakage returned bi monthly injection skipped next injection restored ...

In [79]:
tokenized_text = combi['tidy_text'].apply(lambda x: x.split())
tokenized_text.head()

0    [hello, ,, get, completely, ppms, myself,, really, believe, ppms, folk, least, choice,, us,, canada, europe, take, tecfidera,, complications,, including, deaths, reported, taking, risk, balance, c...
1    [read, entire, thread, going, starting, entyvio, soon, insurance, oks, first, (hopefully, last!), biologic, reason, chose, supposed, systemic, hopefully, make, prone, colds, that's, biggest, worry...
2    [tuesday, pm, et, fda, approved, genentech, ocrevus, tm, (ocrelizumab), people, relapsing, primary, progressive, forms, multiple, sclerosis, (ms), first, approved, treatment, primary, progressive,...
3    [hi, mohit,, welcome, grace, sorry, hear, recent, progression, father, lung, cancer, though, oncologists, like, continue, tarceva, even, progression,, combining, drug, alimta, (pemetrexed),, often...
4    [comment, diagnosed, wet, armd, year, ago, switched, eylea, several, months, ago, initially, profound, impact, reducing, wet, leakage, entirely, leakage, returned, bi, monthly

In [80]:
#Stemming
from nltk.stem.porter import *
stemmer=PorterStemmer()
tokenized_text = tokenized_text.apply(lambda x: [stemmer.stem(i) for i in x])   #stemming
#Lemmatizing - is giving less accurate so used
#from nltk.stem import WordNetLemmatizer 
#lemmatizer = WordNetLemmatizer() 
#tokenized_text1 = tokenized_text.apply(lambda x: [lemmatizer.lemmatize(i) for i in x])   #lemmatizer

Lemmatizing is giving less accurate result so stemming is used

In [81]:
#stitch these tokens back together
for i in range(len(tokenized_text)):
    tokenized_text[i] = ' '.join(tokenized_text[i])
combi['tidy_text'] = tokenized_text

In [82]:
#Bag of Words
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer=CountVectorizer(max_df=0.90,min_df=2,max_features=1000,stop_words='english')
bow = bow_vectorizer.fit_transform(combi['tidy_text'])
print(bow.shape)
bow=pd.DataFrame(bow.toarray())
bow['drug']=combi['drug']
print(bow.shape)

(5215, 1000)
(5215, 1001)


In [83]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer=TfidfVectorizer(max_df=0.90,min_df=2,max_features=1000,stop_words='english')
tfidf = tfidf_vectorizer.fit_transform(combi['tidy_text'])
print(tfidf.shape)
tfidf=pd.DataFrame(tfidf.toarray())
tfidf['drug']=combi['drug']
print(tfidf.shape)

(5215, 1000)
(5215, 1001)


In [84]:
import gensim
tokenized_text = combi['tidy_text'].apply(lambda x: x.split()) # tokenizing 

model_w2v = gensim.models.Word2Vec(
            tokenized_text,
            size=200, # desired no. of features/independent variables-300
            window=5, # context window size -7
            min_count=2,  # Minimum word count threshold
            sg = 1, # 1 for skip-gram model
            hs = 0,
            negative = 10, # for negative sampling
            workers= 4, # no.of cores
            #sampling=#0=1e-3      #Downsample setting for frequent words-  1e-5  
            seed = 34) 
model_w2v.train(tokenized_text, total_examples= len(combi['tidy_text']), epochs=20)

C:\Users\Public\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


(20080289, 21513240)

In [85]:
def word_vector(tokens, size):
    vec = np.zeros(size).reshape((1, size))
    count = 0.
    for word in tokens:
        try:
            vec += model_w2v[word].reshape((1, size))
            count += 1.
        except KeyError: # handling the case where the token is not in vocabulary                                     
            continue
    if count != 0:
        vec /= count
    return vec

In [86]:
#Preparing word2vec feature set…
wordvec_arrays = np.zeros((len(tokenized_text), 200)) 
for i in range(len(tokenized_text)):
    wordvec_arrays[i,:] = word_vector(tokenized_text[i], 200)
wordvec_df = pd.DataFrame(wordvec_arrays) 
print(wordvec_df.shape)   
#Now we have 200 new features, whereas in Bag of Words and TF-IDF we had 1000 features.
wordvec_df['drug']=combi['drug']

(5215, 200)

In [105]:
from tqdm import tqdm 
tqdm.pandas(desc="progress-bar") 
from gensim.models.doc2vec import LabeledSentence

In [106]:
def add_label(twt):
    output = []
    for i, s in zip(twt.index, twt):
        output.append(LabeledSentence(s, ["text_" + str(i)]))
    return output
labeled_texts = add_label(tokenized_text) # label all the tweets

In [107]:
labeled_texts[:6]

[LabeledSentence(words=['hello', ',', 'get', 'complet', 'ppm', 'myself,', 'realli', 'believ', 'ppm', 'folk', 'least', 'choice,', 'us,', 'canada', 'europ', 'take', 'tecfidera,', 'complications,', 'includ', 'death', 'report', 'take', 'risk', 'balanc', 'chosen', 'take', 'peopl', 'die', 'take', 'paracetamol', 'drug', 'risk', 'get', 'drain', 'nh', 'point', 'ocrevu', 'consult', 'document,', 'said', 'ocrevu', 'favour', 'compar', 'cost', 'longer', 'term', 'ppm', 'patient', 'make', 'claim,', 'would', 'let', 'us', 'know', 'project', 'cost', 'lifelong', 'care', 'ppm', 'patient', 'without', 'ocrevus,', 'possibl', 'rrms,', 'long', 'list', 'medications,', 'includ', 'ocrevu', 'elig', 'sister', 'younger', 'me,', 'young', 'kids,', 'ppm', 'unfair', 'access', 'dmd', 'nh', 'prepar', 'fund', 'ocrevus,', 'littl', 'sister', 'ethic', 'standard', 'like', 'say', 'worth', 'invest', 'hey', 'ho,', 'least,', 'latest', 'develop', 'open', 'intellig', 'debate,', 'differ', 'opinion', 'keep', 'site', 'balanc', 'inform',

In [108]:
#Now let’s train a doc2vec model.
model_d2v = gensim.models.Doc2Vec(
    dm=1, # dm = 1 for ‘distributed memory’ model                                  
    dm_mean=1, # dm = 1 for using mean of the context word vectors                                 
    vector_size=200, # no. of desired features                                  
    window=5, # width of the context window                                  
    negative=7, # if > 0 then negative sampling will be used                                 
    min_count=5, # Ignores all words with total frequency lower than 2.                                  
    workers=3, # no. of cores                                  
    alpha=0.1, # learning rate                                  
    seed = 23) 
model_d2v.build_vocab([i for i in tqdm(labeled_texts)])
model_d2v.train(labeled_texts, total_examples= len(combi['tidy_text']), epochs=15)

100%|██████████████████████████████████| 5215/5215 [00:00<00:00, 868987.94it/s]


In [109]:
#Preparing doc2vec Feature Set
docvec_arrays = np.zeros((len(tokenized_text), 200)) 
for i in range(len(combi)):
    docvec_arrays[i,:] = model_d2v.docvecs[i].reshape((1,200))    

docvec_df = pd.DataFrame(docvec_arrays) 
print(docvec_df.shape)
docvec_df['drug']=combi['drug']

(5215, 200)

In [ ]:
# Splitting into  train and test features 
from sklearn.model_selection import train_test_split 
from sklearn.metrics import f1_score , accuracy_score,confusion_matrix , classification_report

# Bag-of-Words Features
train_bow = bow.iloc[:2291,:].values
test_bow = bow.iloc[2291:,:].values 
xtrain_bow, xvalid_bow, ytrain, yvalid = train_test_split(train_bow, train_under['sentiment'], random_state=2,test_size=0.2) #2

#TF_IDF Bag-of-Words Features
train_tfidf = tfidf.iloc[:2291,:].values
test_tfidf = tfidf.iloc[2291:,:].values
xtrain_tfidf = train_tfidf[ytrain.index] 
xvalid_tfidf = train_tfidf[yvalid.index]

train_w2v = wordvec_df.iloc[:2291,:]
test_w2v = wordvec_df.iloc[2291:,:] 
xtrain_w2v = train_w2v.iloc[ytrain.index,:] 
xvalid_w2v = train_w2v.iloc[yvalid.index,:]

#Doc2Vec Features
train_d2v = docvec_df.iloc[:2291,:] 
test_d2v = docvec_df.iloc[2291:,:] 
xtrain_d2v = train_d2v.iloc[ytrain.index,:] 
xvalid_d2v = train_d2v.iloc[yvalid.index,:]

#### RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

#Bag-of-Words Features
rf = RandomForestClassifier(n_estimators=400, random_state=11).fit(xtrain_bow, ytrain) 
prediction = rf.predict(xvalid_bow) 
#print(f1_score(yvalid, prediction) ) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))  
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))


In [103]:

rf1 = RandomForestClassifier(n_estimators=400, random_state=11).fit(train_bow,train_under['sentiment'])
test_pred = rf1.predict(test_bow) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('rf_bow_under.csv', index=False)
#Public Leaderboard F1 Score: 0.448

In [ ]:
#TF-IDF Features
rf = RandomForestClassifier(n_estimators=400, random_state=11).fit(xtrain_tfidf, ytrain) 
prediction = rf.predict(xvalid_tfidf) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))  
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))

#Public Leaderboard F1 Score: 

In [104]:
rf1 = RandomForestClassifier(n_estimators=400, random_state=11).fit(train_tfidf,train_under['sentiment'])
test_pred = rf1.predict(test_tfidf) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('rf_tfidf_under.csv', index=False)

In [39]:
#word 2 vec
rf = RandomForestClassifier(n_estimators=400, random_state=11).fit(xtrain_w2v, ytrain) 
prediction = rf.predict(xvalid_w2v) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))   
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))

#Public Leaderboard F1 Score: 

0.7395833333333334

In [40]:
#doc 2 vec

rf = RandomForestClassifier(n_estimators=400, random_state=11).fit(xtrain_d2v, ytrain) 
prediction = rf.predict(xvalid_d2v) 
print('accuracy',accuracy_score(yvalid, prediction))  #0.7380050505050505
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))

print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))
#Public Leaderboard F1 Score: 

0.7357954545454546

#### XGBoost

In [71]:
#Bag-of-Words Features
from sklearn.model_selection import train_test_split 

from xgboost import XGBClassifier

xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(xtrain_bow, ytrain) 
prediction = xgb_model.predict(xvalid_bow) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))

accuracy 0.49673202614379086
f1score 0.49484416372189405
accuracy [[52 37 41]
 [26 93 45]
 [36 46 83]]
f1score               precision    recall  f1-score   support

           0       0.46      0.40      0.43       130
           1       0.53      0.57      0.55       164
           2       0.49      0.50      0.50       165

   micro avg       0.50      0.50      0.50       459
   macro avg       0.49      0.49      0.49       459
weighted avg       0.49      0.50      0.49       459



In [32]:
xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(train_bow, train1['sentiment']) 
test_pred = xgb_model.predict(test_bow) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('xgb_bowundersampling.csv', index=False)
#Public Leaderboard F1 Score: 0.42

In [95]:
#TF-IDF Features
xgb = XGBClassifier(max_depth=6, n_estimators=1000).fit(xtrain_tfidf, ytrain) 
prediction = xgb.predict(xvalid_tfidf) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))

#Public Leaderboard F1 Score: 0.45

accuracy 0.49673202614379086
f1score 0.49484416372189405
[[52 37 41]
 [26 93 45]
 [36 46 83]]
              precision    recall  f1-score   support

           0       0.46      0.40      0.43       130
           1       0.53      0.57      0.55       164
           2       0.49      0.50      0.50       165

   micro avg       0.50      0.50      0.50       459
   macro avg       0.49      0.49      0.49       459
weighted avg       0.49      0.50      0.49       459



In [97]:
xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(train_tfidf, train_under['sentiment']) 
test_pred = xgb_model.predict(test_tfidf) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('xgb_tfidf_under.csv', index=False)

In [88]:
#Word 2 Vec

xgb = XGBClassifier(max_depth=6, n_estimators=1000, nthread= 3).fit(xtrain_w2v, ytrain) 
prediction = xgb.predict(xvalid_w2v) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))




accuracy 0.49673202614379086
f1score 0.49484416372189405
[[52 37 41]
 [26 93 45]
 [36 46 83]]
              precision    recall  f1-score   support

           0       0.46      0.40      0.43       130
           1       0.53      0.57      0.55       164
           2       0.49      0.50      0.50       165

   micro avg       0.50      0.50      0.50       459
   macro avg       0.49      0.49      0.49       459
weighted avg       0.49      0.50      0.49       459



In [ ]:
xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(train_w2v, train_under['sentiment']) 
test_pred = xgb_model.predict(test_w2v) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('xgb_w2v_under.csv', index=False)
#Public Leaderboard  Score: 0.44

In [72]:
#Doc2Vec Features
xgb = XGBClassifier(max_depth=6, n_estimators=1000, nthread= 3).fit(xtrain_d2v, ytrain) 
prediction = xgb.predict(xvalid_d2v) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted')) 
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))



accuracy 0.7310606060606061
f1score 0.6376817215819405


In [113]:
xgb_model = XGBClassifier(max_depth=6, n_estimators=1000).fit(train_d2v, train_under['sentiment']) 
test_pred = xgb_model.predict(test_d2v) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('xgb_d2v_under.csv', index=False)
#Public Leaderboard  Score: 0.37

#### Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(C=30, class_weight='balanced', solver='sag', 
                         multi_class='multinomial', n_jobs=-1, random_state=40, 
                         verbose=1, max_iter = 1000)
clf.fit(xtrain_bow, ytrain)
prediction = clf.predict(xvalid_bow) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))


In [100]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=30, class_weight='balanced', solver='sag', 
                         multi_class='multinomial', n_jobs=-1, random_state=40, 
                         verbose=1, max_iter = 1000).fit(train_bow, train_under['sentiment']) 
test_pred = clf.predict(test_bow) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('log_bow_under.csv', index=False)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.


max_iter reached after 101 seconds


C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:  1.7min finished


In [ ]:
#word2vec
clf = LogisticRegression(C=30, class_weight='balanced', solver='sag', 
                         multi_class='multinomial', n_jobs=-1, random_state=40, 
                         verbose=1, max_iter = 1000)
clf.fit(xtrain_w2v, ytrain)
prediction = clf.predict(xvalid_w2v) 
print('accuracy',accuracy_score(yvalid, prediction))
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print(confusion_matrix(yvalid, prediction))  
print(classification_report(y_true=yvalid, y_pred=prediction))


In [101]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(C=30, class_weight='balanced', solver='sag', 
                         multi_class='multinomial', n_jobs=-1, random_state=40, 
                         verbose=1, max_iter = 1000).fit(train_w2v, train_under['sentiment']) 
test_pred = clf.predict(test_w2v) 
test['sentiment'] = test_pred 
submission = test[['unique_hash','sentiment']] 
submission.to_csv('log_w2v_under.csv', index=False) 

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 4 concurrent workers.


max_iter reached after 21 seconds


C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\sag.py:334: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
[Parallel(n_jobs=-1)]: Done   1 out of   1 | elapsed:   21.0s finished


#### GaussianNB

In [31]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(xtrain_bow, ytrain)
prediction = clf.predict(xvalid_bow) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print('accuracy',confusion_matrix(yvalid, prediction))  
print('f1score',classification_report(y_true=yvalid, y_pred=prediction))

accuracy 0.5284090909090909
f1score 0.5717391090856773
accuracy [[ 64  23  39]
 [ 38  73  42]
 [185 171 421]]
f1score               precision    recall  f1-score   support

           0       0.22      0.51      0.31       126
           1       0.27      0.48      0.35       153
           2       0.84      0.54      0.66       777

   micro avg       0.53      0.53      0.53      1056
   macro avg       0.45      0.51      0.44      1056
weighted avg       0.68      0.53      0.57      1056



#### SGDClassifier

In [33]:
from sklearn.linear_model import SGDClassifier
sbg=SGDClassifier(loss='modified_huber',shuffle=True,random_state=101).fit(xtrain_bow, ytrain)
prediction = clf.predict(xvalid_bow) 
print('accuracy',accuracy_score(yvalid, prediction))  
print('f1score',f1_score(y_true=yvalid, y_pred=prediction, average='weighted'))
print('accuracy',confusion_matrix(yvalid, prediction))  
print('f1score',classification_report(y_true=yvalid, y_pred=prediction))

C:\Users\Public\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)


accuracy 0.5284090909090909
f1score 0.5717391090856773
accuracy [[ 64  23  39]
 [ 38  73  42]
 [185 171 421]]
f1score               precision    recall  f1-score   support

           0       0.22      0.51      0.31       126
           1       0.27      0.48      0.35       153
           2       0.84      0.54      0.66       777

   micro avg       0.53      0.53      0.53      1056
   macro avg       0.45      0.51      0.44      1056
weighted avg       0.68      0.53      0.57      1056



#### Final Model is Word2Vec model used with under sampling XGBoost
Public Leaderboard F1 Score: 0.4614